services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: writeflow-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s